### PR TITLE
Adding io.py

### PR DESCRIPTION
**Pull request by jdiasn**
Refactoring input/output procedures of the package

### CODE REVIEW

**Comment by castelao** [comment]
Looks good @jdiasn . It might be worth adding at least one test. What about opening one of the netCDFs for testing?

**Comment by jdiasn** [comment]
Thank you for your suggestion @castelao! Adding a test is a good idea. I will work on it.

**Review by castelao — APPROVED** [review]

**Comment by castelao** [comment]
@jdias, I'm looking at dataOperator.dataOperations.elevationFilter(). I think that this is another place where it would be best to split I/O operations from pre-processing. I think it would be best to move the merging procedure outside there, so it expects an xr.Dataset and handles whatever it has. Thus the merging multiple files would be done before. This would isolate better the procedures and give more flexibility to that pre-processing.

If you agree with that, we might use xr.open_mfdataset or create a modified version of that on top of this PR here. What do you think?

**Comment by jdiasn** [comment]
@castelao I like your suggestion, and I think it is a good idea to merge the data before hands. I initially thought of using xr.open_mfdataset for accessing all files at once, but I did not know how to access the netCDF groups using the xr.open_mfdataset. Another reason is that the range coordinate does not have the same size and values for all files from the 6-beam scanning strategy. The files from the zenith have a range coordinate, while the files from the slanted observations have another range coordinate. However, the data with the same index are from the same height. 


Maybe I did not mention it before, but dataOperator.dataOperations.elevationFilter() is only applied to the 6-beam files. In the same dataOperator module, there is another class called dbsOperations (have a look). The dbsOperations only deal with the DBS files and merge them. For those files, the elevationFilter is not needed. The DBS files do not have a range coordinate; instead, they have a gate_index coordinate and another variable where the height is written. Maybe it would be possible to use the xr.open_mfdataset for the DBS files.

**Comment by jdiasn** [comment]
I am closing this PR

**Pull request merged**
